### ISSUE TITLE
Is the target of this document specifically partners?

### ISSUE THREAD

**Issue by tchughesiv** [jdob/ocp-onboard#2]
If so, we probably need to address more "container cert requirements" over time... which i can help with:
e.g.
 - help file
 - vulnerabilities updates
 - rpm verify?
 - optional labels?
 - etc.

Also,
We're working on more "official" documentation around help files, good practices, and handling arbitrary uids which we'll be able to link to eventually.

**Comment by jdob** [comment]
The scope is fuzzy :) I could see adding a specific page about certification, perhaps linking to existing docs when they exist.

My current thinking is that this is to help people just get *something* up and running as quickly as possible. The short path to getting something deployed and knowing where to look for the next steps. But I really like the idea of there being a "Next Steps" section that talks about bridging the gap between "work with duct tape" to "something Red Hat will actually acknowledge".

**Comment by jdob** [comment]
I'm going to close this out. With the certification guide nearly finished, I think that fills the needs that go beyond the scope of this.
